window.esdocSearchIndex = [
  [
    "gisplay-es6-webpack/src/gisplay/maps/aesthetic.js~aesthetic",
    "class/src/Gisplay/Maps/Aesthetic.js~Aesthetic.html",
    "<span>Aesthetic</span> <span class=\"search-result-import-path\">gisplay-es6-webpack/src/Gisplay/Maps/Aesthetic.js</span>",
    "class"
  ],
  [
    "gisplay-es6-webpack/src/gisplay/maps/bgmapwrapper.js~bgmapwrapper",
    "class/src/Gisplay/Maps/BGMapWrapper.js~BGMapWrapper.html",
    "<span>BGMapWrapper</span> <span class=\"search-result-import-path\">gisplay-es6-webpack/src/Gisplay/Maps/BGMapWrapper.js</span>",
    "class"
  ],
  [
    "gisplay-es6-webpack/src/gisplay/maps/types/changemap.js~changemap",
    "class/src/Gisplay/Maps/Types/ChangeMap.js~ChangeMap.html",
    "<span>ChangeMap</span> <span class=\"search-result-import-path\">gisplay-es6-webpack/src/Gisplay/Maps/Types/ChangeMap.js</span>",
    "class"
  ],
  [
    "gisplay-es6-webpack/src/gisplay/maps/types/chorochromaticmap.js~chorochromaticmap",
    "class/src/Gisplay/Maps/Types/ChorochromaticMap.js~ChorochromaticMap.html",
    "<span>ChorochromaticMap</span> <span class=\"search-result-import-path\">gisplay-es6-webpack/src/Gisplay/Maps/Types/ChorochromaticMap.js</span>",
    "class"
  ],
  [
    "gisplay-es6-webpack/src/gisplay/maps/types/choropleth.js~choropleth",
    "class/src/Gisplay/Maps/Types/Choropleth.js~Choropleth.html",
    "<span>Choropleth</span> <span class=\"search-result-import-path\">gisplay-es6-webpack/src/Gisplay/Maps/Types/Choropleth.js</span>",
    "class"
  ],
  [
    "gisplay-es6-webpack/src/gisplay/maps/v11/choroplethgooglemaps.js~choroplethgooglemaps",
    "class/src/Gisplay/Maps/v11/ChoroplethGoogleMaps.js~ChoroplethGoogleMaps.html",
    "<span>ChoroplethGoogleMaps</span> <span class=\"search-result-import-path\">gisplay-es6-webpack/src/Gisplay/Maps/v11/ChoroplethGoogleMaps.js</span>",
    "class"
  ],
  [
    "gisplay-es6-webpack/src/gisplay/maps/types/dotmap.js~dotmap",
    "class/src/Gisplay/Maps/Types/DotMap.js~DotMap.html",
    "<span>DotMap</span> <span class=\"search-result-import-path\">gisplay-es6-webpack/src/Gisplay/Maps/Types/DotMap.js</span>",
    "class"
  ],
  [
    "gisplay-es6-webpack/src/gisplay/maps/feature.js~feature",
    "class/src/Gisplay/Maps/Feature.js~Feature.html",
    "<span>Feature</span> <span class=\"search-result-import-path\">gisplay-es6-webpack/src/Gisplay/Maps/Feature.js</span>",
    "class"
  ],
  [
    "gisplay-es6-webpack/src/gisplay/gisplay.js~gisplay",
    "class/src/Gisplay/Gisplay.js~Gisplay.html",
    "<span>Gisplay</span> <span class=\"search-result-import-path\">gisplay-es6-webpack/src/Gisplay/Gisplay.js</span>",
    "class"
  ],
  [
    "gisplay-es6-webpack/src/gisplay/gisplayoptions.js~gisplayoptions",
    "class/src/Gisplay/GisplayOptions.js~GisplayOptions.html",
    "<span>GisplayOptions</span> <span class=\"search-result-import-path\">gisplay-es6-webpack/src/Gisplay/GisplayOptions.js</span>",
    "class"
  ],
  [
    "gisplay-es6-webpack/src/gisplay/maps/v11/googlemapsbgmap.js~googlemapsbgmap",
    "class/src/Gisplay/Maps/v11/GoogleMapsBGMap.js~GoogleMapsBGMap.html",
    "<span>GoogleMapsBGMap</span> <span class=\"search-result-import-path\">gisplay-es6-webpack/src/Gisplay/Maps/v11/GoogleMapsBGMap.js</span>",
    "class"
  ],
  [
    "gisplay-es6-webpack/src/gisplay/maps/legend.js~legend",
    "class/src/Gisplay/Maps/Legend.js~Legend.html",
    "<span>Legend</span> <span class=\"search-result-import-path\">gisplay-es6-webpack/src/Gisplay/Maps/Legend.js</span>",
    "class"
  ],
  [
    "gisplay-es6-webpack/src/gisplay/maps/map.js~map",
    "class/src/Gisplay/Maps/Map.js~Map.html",
    "<span>Map</span> <span class=\"search-result-import-path\">gisplay-es6-webpack/src/Gisplay/Maps/Map.js</span>",
    "class"
  ],
  [
    "gisplay-es6-webpack/src/gisplay/maps/types/proportionalsymbolsmap.js~proportionalsymbolsmap",
    "class/src/Gisplay/Maps/Types/ProportionalSymbolsMap.js~ProportionalSymbolsMap.html",
    "<span>ProportionalSymbolsMap</span> <span class=\"search-result-import-path\">gisplay-es6-webpack/src/Gisplay/Maps/Types/ProportionalSymbolsMap.js</span>",
    "class"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~audiocontext",
    "https://developer.mozilla.org/en/docs/Web/API/AudioContext",
    "BuiltinExternal/WebAPIExternal.js~AudioContext",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "https://developer.mozilla.org/en-US/docs/Web/API/DocumentFragment",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "https://developer.mozilla.org/en-US/docs/Web/API/Element",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "https://developer.mozilla.org/en-US/docs/Web/API/Event",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "https://developer.mozilla.org/en-US/docs/Web/API/Node",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "https://developer.mozilla.org/en-US/docs/Web/API/NodeList",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "https://developer.mozilla.org/en/docs/Web/API/XMLHttpRequest",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "gisplayoptions src/gisplay/gisplayoptions.js~gisplayoptions,gisplayoptions",
    "test-file/test/test.js.html#lineNumber158",
    "Test GisplayOptions. Some user options are defined. TODO: More testing",
    "test"
  ],
  [
    "gisplayoptions#attr src/gisplay/gisplayoptions.js~gisplayoptions#attr,gisplayoptions#attr",
    "test-file/test/test.js.html#lineNumber165",
    "Test GisplayOptions. Some user options are defined. TODO: More testing Attr value is undefined",
    "test"
  ],
  [
    "gisplayoptions#colorscheme src/gisplay/gisplayoptions.js~gisplayoptions#colorscheme,gisplayoptions#colorscheme",
    "test-file/test/test.js.html#lineNumber170",
    "Test GisplayOptions. Some user options are defined. TODO: More testing Color Shceme is undefined",
    "test"
  ],
  [
    "gisplayoptions#alpha src/gisplay/gisplayoptions.js~gisplayoptions#alpha,gisplayoptions#alpha",
    "test-file/test/test.js.html#lineNumber266",
    "Test GisplayOptions. Some user options are defined. TODO: More testing alpha is 0.8",
    "test"
  ],
  [
    "gisplayoptions#classbreaks src/gisplay/gisplayoptions.js~gisplayoptions#classbreaks,gisplayoptions#classbreaks",
    "test-file/test/test.js.html#lineNumber185",
    "Test GisplayOptions. Some user options are defined. TODO: More testing classBreaks are undefined",
    "test"
  ],
  [
    "gisplayoptions#classbreaksmethod src/gisplay/gisplayoptions.js~gisplayoptions#classbreaksmethod,gisplayoptions#classbreaksmethod",
    "test-file/test/test.js.html#lineNumber180",
    "Test GisplayOptions. Some user options are defined. TODO: More testing classBreaksMethod is quantile",
    "test"
  ],
  [
    "gisplayoptions#colorschemeid src/gisplay/gisplayoptions.js~gisplayoptions#colorschemeid,gisplayoptions#colorschemeid",
    "test-file/test/test.js.html#lineNumber250",
    "Test GisplayOptions. Some user options are defined. TODO: More testing colorSchemeId is 1",
    "test"
  ],
  [
    "gisplayoptions#interactive src/gisplay/gisplayoptions.js~gisplayoptions#interactive,gisplayoptions#interactive",
    "test-file/test/test.js.html#lineNumber190",
    "Test GisplayOptions. Some user options are defined. TODO: More testing interactive is true ",
    "test"
  ],
  [
    "gisplayoptions#isdynamic src/gisplay/gisplayoptions.js~gisplayoptions#isdynamic,gisplayoptions#isdynamic",
    "test-file/test/test.js.html#lineNumber282",
    "Test GisplayOptions. Some user options are defined. TODO: More testing isDynamic is !memorySaver(true)",
    "test"
  ],
  [
    "gisplayoptions#legendonclickfunction src/gisplay/gisplayoptions.js~gisplayoptions#legendonclickfunction,gisplayoptions#legendonclickfunction",
    "test-file/test/test.js.html#lineNumber255",
    "Test GisplayOptions. Some user options are defined. TODO: More testing legendOnClickFunction is undefined",
    "test"
  ],
  [
    "gisplayoptions#legendtitle src/gisplay/gisplayoptions.js~gisplayoptions#legendtitle,gisplayoptions#legendtitle",
    "test-file/test/test.js.html#lineNumber215",
    "Test GisplayOptions. Some user options are defined. TODO: More testing legendTitle is undefined - undefined",
    "test"
  ],
  [
    "gisplayoptions#legendtoggle src/gisplay/gisplayoptions.js~gisplayoptions#legendtoggle,gisplayoptions#legendtoggle",
    "test-file/test/test.js.html#lineNumber287",
    "Test GisplayOptions. Some user options are defined. TODO: More testing legendToggle is true",
    "test"
  ],
  [
    "gisplayoptions#maponclickfunction src/gisplay/gisplayoptions.js~gisplayoptions#maponclickfunction,gisplayoptions#maponclickfunction",
    "test-file/test/test.js.html#lineNumber260",
    "Test GisplayOptions. Some user options are defined. TODO: More testing mapOnClickFunction  is undefined",
    "test"
  ],
  [
    "gisplayoptions#maxfeatures src/gisplay/gisplayoptions.js~gisplayoptions#maxfeatures,gisplayoptions#maxfeatures",
    "test-file/test/test.js.html#lineNumber271",
    "Test GisplayOptions. Some user options are defined. TODO: More testing maxFeatures is equal to Number.MAX_VALUE",
    "test"
  ],
  [
    "gisplayoptions#maxpointsize src/gisplay/gisplayoptions.js~gisplayoptions#maxpointsize,gisplayoptions#maxpointsize",
    "test-file/test/test.js.html#lineNumber235",
    "Test GisplayOptions. Some user options are defined. TODO: More testing maxPointSize is 10.0",
    "test"
  ],
  [
    "gisplayoptions#memorysaver src/gisplay/gisplayoptions.js~gisplayoptions#memorysaver,gisplayoptions#memorysaver",
    "test-file/test/test.js.html#lineNumber245",
    "Test GisplayOptions. Some user options are defined. TODO: More testing memorySaver is true",
    "test"
  ],
  [
    "gisplayoptions#minpointsize src/gisplay/gisplayoptions.js~gisplayoptions#minpointsize,gisplayoptions#minpointsize",
    "test-file/test/test.js.html#lineNumber230",
    "Test GisplayOptions. Some user options are defined. TODO: More testing minPointSize is 1.0",
    "test"
  ],
  [
    "gisplayoptions#minuend src/gisplay/gisplayoptions.js~gisplayoptions#minuend,gisplayoptions#minuend",
    "test-file/test/test.js.html#lineNumber205",
    "Test GisplayOptions. Some user options are defined. TODO: More testing minuend is undefined ",
    "test"
  ],
  [
    "gisplayoptions#numberofclasses src/gisplay/gisplayoptions.js~gisplayoptions#numberofclasses,gisplayoptions#numberofclasses",
    "test-file/test/test.js.html#lineNumber175",
    "Test GisplayOptions. Some user options are defined. TODO: More testing numberOfClasses is undefined",
    "test"
  ],
  [
    "gisplayoptions#numberoflegenditems src/gisplay/gisplayoptions.js~gisplayoptions#numberoflegenditems,gisplayoptions#numberoflegenditems",
    "test-file/test/test.js.html#lineNumber276",
    "Test GisplayOptions. Some user options are defined. TODO: More testing numberOfLegendItems is 2",
    "test"
  ],
  [
    "gisplayoptions#showlegend src/gisplay/gisplayoptions.js~gisplayoptions#showlegend,gisplayoptions#showlegend",
    "test-file/test/test.js.html#lineNumber200",
    "Test GisplayOptions. Some user options are defined. TODO: More testing showLegend is true",
    "test"
  ],
  [
    "gisplayoptions#showloader src/gisplay/gisplayoptions.js~gisplayoptions#showloader,gisplayoptions#showloader",
    "test-file/test/test.js.html#lineNumber220",
    "Test GisplayOptions. Some user options are defined. TODO: More testing showLoader is true",
    "test"
  ],
  [
    "gisplayoptions#showpropertiesonclick src/gisplay/gisplayoptions.js~gisplayoptions#showpropertiesonclick,gisplayoptions#showpropertiesonclick",
    "test-file/test/test.js.html#lineNumber195",
    "Test GisplayOptions. Some user options are defined. TODO: More testing showPropertiesOnClick is null ",
    "test"
  ],
  [
    "gisplayoptions#sizebyclass src/gisplay/gisplayoptions.js~gisplayoptions#sizebyclass,gisplayoptions#sizebyclass",
    "test-file/test/test.js.html#lineNumber240",
    "Test GisplayOptions. Some user options are defined. TODO: More testing sizeByClass is false",
    "test"
  ],
  [
    "gisplayoptions#subtrahend src/gisplay/gisplayoptions.js~gisplayoptions#subtrahend,gisplayoptions#subtrahend",
    "test-file/test/test.js.html#lineNumber210",
    "Test GisplayOptions. Some user options are defined. TODO: More testing subtrahend is undefined ",
    "test"
  ],
  [
    "gisplayoptions#usecustommapservice src/gisplay/gisplayoptions.js~gisplayoptions#usecustommapservice,gisplayoptions#usecustommapservice",
    "test-file/test/test.js.html#lineNumber225",
    "Test GisplayOptions. Some user options are defined. TODO: More testing useCustomMapService is false ",
    "test"
  ],
  [
    "gisplayoptions src/gisplay/gisplayoptions.js~gisplayoptions,gisplayoptions",
    "test-file/test/test.js.html#lineNumber5",
    "Test GisplayOptions. User options are empty so all defaults should be used.",
    "test"
  ],
  [
    "gisplayoptions#attr src/gisplay/gisplayoptions.js~gisplayoptions#attr,gisplayoptions#attr",
    "test-file/test/test.js.html#lineNumber9",
    "Test GisplayOptions. User options are empty so all defaults should be used. Attr value is undefined",
    "test"
  ],
  [
    "gisplayoptions#colorscheme src/gisplay/gisplayoptions.js~gisplayoptions#colorscheme,gisplayoptions#colorscheme",
    "test-file/test/test.js.html#lineNumber14",
    "Test GisplayOptions. User options are empty so all defaults should be used. Color Shceme is undefined",
    "test"
  ],
  [
    "gisplayoptions#alpha src/gisplay/gisplayoptions.js~gisplayoptions#alpha,gisplayoptions#alpha",
    "test-file/test/test.js.html#lineNumber110",
    "Test GisplayOptions. User options are empty so all defaults should be used. alpha is 0.8",
    "test"
  ],
  [
    "gisplayoptions#classbreaks src/gisplay/gisplayoptions.js~gisplayoptions#classbreaks,gisplayoptions#classbreaks",
    "test-file/test/test.js.html#lineNumber29",
    "Test GisplayOptions. User options are empty so all defaults should be used. classBreaks are undefined",
    "test"
  ],
  [
    "gisplayoptions#classbreaksmethod src/gisplay/gisplayoptions.js~gisplayoptions#classbreaksmethod,gisplayoptions#classbreaksmethod",
    "test-file/test/test.js.html#lineNumber24",
    "Test GisplayOptions. User options are empty so all defaults should be used. classBreaksMethod is quantile",
    "test"
  ],
  [
    "gisplayoptions#colorschemeid src/gisplay/gisplayoptions.js~gisplayoptions#colorschemeid,gisplayoptions#colorschemeid",
    "test-file/test/test.js.html#lineNumber94",
    "Test GisplayOptions. User options are empty so all defaults should be used. colorSchemeId is 1",
    "test"
  ],
  [
    "gisplayoptions#intensity src/gisplay/gisplayoptions.js~gisplayoptions#intensity,gisplayoptions#intensity",
    "test-file/test/test.js.html#lineNumber137",
    "Test GisplayOptions. User options are empty so all defaults should be used. intensity(deprecated) is 1.0",
    "test"
  ],
  [
    "gisplayoptions#interactive src/gisplay/gisplayoptions.js~gisplayoptions#interactive,gisplayoptions#interactive",
    "test-file/test/test.js.html#lineNumber34",
    "Test GisplayOptions. User options are empty so all defaults should be used. interactive is true ",
    "test"
  ],
  [
    "gisplayoptions#isdynamic src/gisplay/gisplayoptions.js~gisplayoptions#isdynamic,gisplayoptions#isdynamic",
    "test-file/test/test.js.html#lineNumber126",
    "Test GisplayOptions. User options are empty so all defaults should be used. isDynamic is !memorySaver(true)",
    "test"
  ],
  [
    "gisplayoptions#legendnumberformat src/gisplay/gisplayoptions.js~gisplayoptions#legendnumberformat,gisplayoptions#legendnumberformat",
    "test-file/test/test.js.html#lineNumber147",
    "Test GisplayOptions. User options are empty so all defaults should be used. legendNumberFormat(deprecated) is 0",
    "test"
  ],
  [
    "gisplayoptions#legendonclickfunction src/gisplay/gisplayoptions.js~gisplayoptions#legendonclickfunction,gisplayoptions#legendonclickfunction",
    "test-file/test/test.js.html#lineNumber99",
    "Test GisplayOptions. User options are empty so all defaults should be used. legendOnClickFunction is undefined",
    "test"
  ],
  [
    "gisplayoptions# gisplayoptions#,gisplayoptions#",
    "test-file/test/test.js.html#lineNumber142",
    "Test GisplayOptions. User options are empty so all defaults should be used. legendPosition(deprecated) is equal to br",
    "test"
  ],
  [
    "gisplayoptions#legendtitle src/gisplay/gisplayoptions.js~gisplayoptions#legendtitle,gisplayoptions#legendtitle",
    "test-file/test/test.js.html#lineNumber59",
    "Test GisplayOptions. User options are empty so all defaults should be used. legendTitle is undefined - undefined",
    "test"
  ],
  [
    "gisplayoptions#legendtoggle src/gisplay/gisplayoptions.js~gisplayoptions#legendtoggle,gisplayoptions#legendtoggle",
    "test-file/test/test.js.html#lineNumber131",
    "Test GisplayOptions. User options are empty so all defaults should be used. legendToggle is true",
    "test"
  ],
  [
    "gisplayoptions#maponclickfunction src/gisplay/gisplayoptions.js~gisplayoptions#maponclickfunction,gisplayoptions#maponclickfunction",
    "test-file/test/test.js.html#lineNumber104",
    "Test GisplayOptions. User options are empty so all defaults should be used. mapOnClickFunction  is undefined",
    "test"
  ],
  [
    "gisplayoptions#maxfeatures src/gisplay/gisplayoptions.js~gisplayoptions#maxfeatures,gisplayoptions#maxfeatures",
    "test-file/test/test.js.html#lineNumber115",
    "Test GisplayOptions. User options are empty so all defaults should be used. maxFeatures is equal to Number.MAX_VALUE",
    "test"
  ],
  [
    "gisplayoptions#maxpointsize src/gisplay/gisplayoptions.js~gisplayoptions#maxpointsize,gisplayoptions#maxpointsize",
    "test-file/test/test.js.html#lineNumber79",
    "Test GisplayOptions. User options are empty so all defaults should be used. maxPointSize is 10.0",
    "test"
  ],
  [
    "gisplayoptions#memorysaver src/gisplay/gisplayoptions.js~gisplayoptions#memorysaver,gisplayoptions#memorysaver",
    "test-file/test/test.js.html#lineNumber89",
    "Test GisplayOptions. User options are empty so all defaults should be used. memorySaver is true",
    "test"
  ],
  [
    "gisplayoptions#minpointsize src/gisplay/gisplayoptions.js~gisplayoptions#minpointsize,gisplayoptions#minpointsize",
    "test-file/test/test.js.html#lineNumber74",
    "Test GisplayOptions. User options are empty so all defaults should be used. minPointSize is 1.0",
    "test"
  ],
  [
    "gisplayoptions#minuend src/gisplay/gisplayoptions.js~gisplayoptions#minuend,gisplayoptions#minuend",
    "test-file/test/test.js.html#lineNumber49",
    "Test GisplayOptions. User options are empty so all defaults should be used. minuend is undefined ",
    "test"
  ],
  [
    "gisplayoptions#numberofclasses src/gisplay/gisplayoptions.js~gisplayoptions#numberofclasses,gisplayoptions#numberofclasses",
    "test-file/test/test.js.html#lineNumber19",
    "Test GisplayOptions. User options are empty so all defaults should be used. numberOfClasses is undefined",
    "test"
  ],
  [
    "gisplayoptions#numberoflegenditems src/gisplay/gisplayoptions.js~gisplayoptions#numberoflegenditems,gisplayoptions#numberoflegenditems",
    "test-file/test/test.js.html#lineNumber120",
    "Test GisplayOptions. User options are empty so all defaults should be used. numberOfLegendItems is 2",
    "test"
  ],
  [
    "gisplayoptions# gisplayoptions#,gisplayoptions#",
    "test-file/test/test.js.html#lineNumber152",
    "Test GisplayOptions. User options are empty so all defaults should be used. profiling is true",
    "test"
  ],
  [
    "gisplayoptions#showlegend src/gisplay/gisplayoptions.js~gisplayoptions#showlegend,gisplayoptions#showlegend",
    "test-file/test/test.js.html#lineNumber44",
    "Test GisplayOptions. User options are empty so all defaults should be used. showLegend is true",
    "test"
  ],
  [
    "gisplayoptions#showloader src/gisplay/gisplayoptions.js~gisplayoptions#showloader,gisplayoptions#showloader",
    "test-file/test/test.js.html#lineNumber64",
    "Test GisplayOptions. User options are empty so all defaults should be used. showLoader is true",
    "test"
  ],
  [
    "gisplayoptions#showpropertiesonclick src/gisplay/gisplayoptions.js~gisplayoptions#showpropertiesonclick,gisplayoptions#showpropertiesonclick",
    "test-file/test/test.js.html#lineNumber39",
    "Test GisplayOptions. User options are empty so all defaults should be used. showPropertiesOnClick is null ",
    "test"
  ],
  [
    "gisplayoptions#sizebyclass src/gisplay/gisplayoptions.js~gisplayoptions#sizebyclass,gisplayoptions#sizebyclass",
    "test-file/test/test.js.html#lineNumber84",
    "Test GisplayOptions. User options are empty so all defaults should be used. sizeByClass is false",
    "test"
  ],
  [
    "gisplayoptions#subtrahend src/gisplay/gisplayoptions.js~gisplayoptions#subtrahend,gisplayoptions#subtrahend",
    "test-file/test/test.js.html#lineNumber54",
    "Test GisplayOptions. User options are empty so all defaults should be used. subtrahend is undefined ",
    "test"
  ],
  [
    "gisplayoptions#usecustommapservice src/gisplay/gisplayoptions.js~gisplayoptions#usecustommapservice,gisplayoptions#usecustommapservice",
    "test-file/test/test.js.html#lineNumber69",
    "Test GisplayOptions. User options are empty so all defaults should be used. useCustomMapService is false ",
    "test"
  ],
  [
    "src/gisplay/gisplay.js",
    "file/src/Gisplay/Gisplay.js.html",
    "src/Gisplay/Gisplay.js",
    "file"
  ],
  [
    "src/gisplay/gisplay.js~gisplay#constructor",
    "class/src/Gisplay/Gisplay.js~Gisplay.html#instance-constructor-constructor",
    "src/Gisplay/Gisplay.js~Gisplay#constructor",
    "method"
  ],
  [
    "src/gisplay/gisplay.js~gisplay#makechangemap",
    "class/src/Gisplay/Gisplay.js~Gisplay.html#instance-method-makeChangeMap",
    "src/Gisplay/Gisplay.js~Gisplay#makeChangeMap",
    "method"
  ],
  [
    "src/gisplay/gisplay.js~gisplay#makechorochromaticmap",
    "class/src/Gisplay/Gisplay.js~Gisplay.html#instance-method-makeChorochromaticMap",
    "src/Gisplay/Gisplay.js~Gisplay#makeChorochromaticMap",
    "method"
  ],
  [
    "src/gisplay/gisplay.js~gisplay#makechoropleth",
    "class/src/Gisplay/Gisplay.js~Gisplay.html#instance-method-makeChoropleth",
    "src/Gisplay/Gisplay.js~Gisplay#makeChoropleth",
    "method"
  ],
  [
    "src/gisplay/gisplay.js~gisplay#makechoroplethgooglemaps",
    "class/src/Gisplay/Gisplay.js~Gisplay.html#instance-method-makeChoroplethGoogleMaps",
    "src/Gisplay/Gisplay.js~Gisplay#makeChoroplethGoogleMaps",
    "method"
  ],
  [
    "src/gisplay/gisplay.js~gisplay#makedotmap",
    "class/src/Gisplay/Gisplay.js~Gisplay.html#instance-method-makeDotMap",
    "src/Gisplay/Gisplay.js~Gisplay#makeDotMap",
    "method"
  ],
  [
    "src/gisplay/gisplay.js~gisplay#makeproportionalsymbolsmap",
    "class/src/Gisplay/Gisplay.js~Gisplay.html#instance-method-makeProportionalSymbolsMap",
    "src/Gisplay/Gisplay.js~Gisplay#makeProportionalSymbolsMap",
    "method"
  ],
  [
    "src/gisplay/gisplay.js~gisplay#starttimestamp",
    "class/src/Gisplay/Gisplay.js~Gisplay.html#instance-member-startTimeStamp",
    "src/Gisplay/Gisplay.js~Gisplay#startTimeStamp",
    "member"
  ],
  [
    "src/gisplay/gisplayoptions.js",
    "file/src/Gisplay/GisplayOptions.js.html",
    "src/Gisplay/GisplayOptions.js",
    "file"
  ],
  [
    "src/gisplay/gisplayoptions.js~gisplayoptions#alpha",
    "class/src/Gisplay/GisplayOptions.js~GisplayOptions.html#instance-member-alpha",
    "src/Gisplay/GisplayOptions.js~GisplayOptions#alpha",
    "member"
  ],
  [
    "src/gisplay/gisplayoptions.js~gisplayoptions#attr",
    "class/src/Gisplay/GisplayOptions.js~GisplayOptions.html#instance-member-attr",
    "src/Gisplay/GisplayOptions.js~GisplayOptions#attr",
    "member"
  ],
  [
    "src/gisplay/gisplayoptions.js~gisplayoptions#classbreaks",
    "class/src/Gisplay/GisplayOptions.js~GisplayOptions.html#instance-member-classBreaks",
    "src/Gisplay/GisplayOptions.js~GisplayOptions#classBreaks",
    "member"
  ],
  [
    "src/gisplay/gisplayoptions.js~gisplayoptions#classbreaksmethod",
    "class/src/Gisplay/GisplayOptions.js~GisplayOptions.html#instance-member-classBreaksMethod",
    "src/Gisplay/GisplayOptions.js~GisplayOptions#classBreaksMethod",
    "member"
  ],
  [
    "src/gisplay/gisplayoptions.js~gisplayoptions#colorscheme",
    "class/src/Gisplay/GisplayOptions.js~GisplayOptions.html#instance-member-colorScheme",
    "src/Gisplay/GisplayOptions.js~GisplayOptions#colorScheme",
    "member"
  ],
  [
    "src/gisplay/gisplayoptions.js~gisplayoptions#colorschemeid",
    "class/src/Gisplay/GisplayOptions.js~GisplayOptions.html#instance-member-colorSchemeId",
    "src/Gisplay/GisplayOptions.js~GisplayOptions#colorSchemeId",
    "member"
  ],
  [
    "src/gisplay/gisplayoptions.js~gisplayoptions#constructor",
    "class/src/Gisplay/GisplayOptions.js~GisplayOptions.html#instance-constructor-constructor",
    "src/Gisplay/GisplayOptions.js~GisplayOptions#constructor",
    "method"
  ],
  [
    "src/gisplay/gisplayoptions.js~gisplayoptions#getavailableclassbreaksmethods",
    "class/src/Gisplay/GisplayOptions.js~GisplayOptions.html#instance-method-getAvailableClassBreaksMethods",
    "src/Gisplay/GisplayOptions.js~GisplayOptions#getAvailableClassBreaksMethods",
    "method"
  ],
  [
    "src/gisplay/gisplayoptions.js~gisplayoptions#intensity",
    "class/src/Gisplay/GisplayOptions.js~GisplayOptions.html#instance-member-intensity",
    "src/Gisplay/GisplayOptions.js~GisplayOptions#intensity",
    "member"
  ],
  [
    "src/gisplay/gisplayoptions.js~gisplayoptions#interactive",
    "class/src/Gisplay/GisplayOptions.js~GisplayOptions.html#instance-member-interactive",
    "src/Gisplay/GisplayOptions.js~GisplayOptions#interactive",
    "member"
  ],
  [
    "src/gisplay/gisplayoptions.js~gisplayoptions#isdynamic",
    "class/src/Gisplay/GisplayOptions.js~GisplayOptions.html#instance-member-isDynamic",
    "src/Gisplay/GisplayOptions.js~GisplayOptions#isDynamic",
    "member"
  ],
  [
    "src/gisplay/gisplayoptions.js~gisplayoptions#legendnumberformat",
    "class/src/Gisplay/GisplayOptions.js~GisplayOptions.html#instance-member-legendNumberFormat",
    "src/Gisplay/GisplayOptions.js~GisplayOptions#legendNumberFormat",
    "member"
  ],
  [
    "src/gisplay/gisplayoptions.js~gisplayoptions#legendonclickfunction",
    "class/src/Gisplay/GisplayOptions.js~GisplayOptions.html#instance-member-legendOnClickFunction",
    "src/Gisplay/GisplayOptions.js~GisplayOptions#legendOnClickFunction",
    "member"
  ],
  [
    "src/gisplay/gisplayoptions.js~gisplayoptions#legendposition",
    "class/src/Gisplay/GisplayOptions.js~GisplayOptions.html#instance-member-legendPosition",
    "src/Gisplay/GisplayOptions.js~GisplayOptions#legendPosition",
    "member"
  ],
  [
    "src/gisplay/gisplayoptions.js~gisplayoptions#legendtitle",
    "class/src/Gisplay/GisplayOptions.js~GisplayOptions.html#instance-member-legendTitle",
    "src/Gisplay/GisplayOptions.js~GisplayOptions#legendTitle",
    "member"
  ],
  [
    "src/gisplay/gisplayoptions.js~gisplayoptions#legendtoggle",
    "class/src/Gisplay/GisplayOptions.js~GisplayOptions.html#instance-member-legendToggle",
    "src/Gisplay/GisplayOptions.js~GisplayOptions#legendToggle",
    "member"
  ],
  [
    "src/gisplay/gisplayoptions.js~gisplayoptions#maponclickfunction",
    "class/src/Gisplay/GisplayOptions.js~GisplayOptions.html#instance-member-mapOnClickFunction",
    "src/Gisplay/GisplayOptions.js~GisplayOptions#mapOnClickFunction",
    "member"
  ],
  [
    "src/gisplay/gisplayoptions.js~gisplayoptions#maxfeatures",
    "class/src/Gisplay/GisplayOptions.js~GisplayOptions.html#instance-member-maxFeatures",
    "src/Gisplay/GisplayOptions.js~GisplayOptions#maxFeatures",
    "member"
  ],
  [
    "src/gisplay/gisplayoptions.js~gisplayoptions#maxpointsize",
    "class/src/Gisplay/GisplayOptions.js~GisplayOptions.html#instance-member-maxPointSize",
    "src/Gisplay/GisplayOptions.js~GisplayOptions#maxPointSize",
    "member"
  ],
  [
    "src/gisplay/gisplayoptions.js~gisplayoptions#memorysaver",
    "class/src/Gisplay/GisplayOptions.js~GisplayOptions.html#instance-member-memorySaver",
    "src/Gisplay/GisplayOptions.js~GisplayOptions#memorySaver",
    "member"
  ],
  [
    "src/gisplay/gisplayoptions.js~gisplayoptions#minpointsize",
    "class/src/Gisplay/GisplayOptions.js~GisplayOptions.html#instance-member-minPointSize",
    "src/Gisplay/GisplayOptions.js~GisplayOptions#minPointSize",
    "member"
  ],
  [
    "src/gisplay/gisplayoptions.js~gisplayoptions#minuend",
    "class/src/Gisplay/GisplayOptions.js~GisplayOptions.html#instance-member-minuend",
    "src/Gisplay/GisplayOptions.js~GisplayOptions#minuend",
    "member"
  ],
  [
    "src/gisplay/gisplayoptions.js~gisplayoptions#numberofclasses",
    "class/src/Gisplay/GisplayOptions.js~GisplayOptions.html#instance-member-numberOfClasses",
    "src/Gisplay/GisplayOptions.js~GisplayOptions#numberOfClasses",
    "member"
  ],
  [
    "src/gisplay/gisplayoptions.js~gisplayoptions#numberoflegenditems",
    "class/src/Gisplay/GisplayOptions.js~GisplayOptions.html#instance-member-numberOfLegendItems",
    "src/Gisplay/GisplayOptions.js~GisplayOptions#numberOfLegendItems",
    "member"
  ],
  [
    "src/gisplay/gisplayoptions.js~gisplayoptions#profiling",
    "class/src/Gisplay/GisplayOptions.js~GisplayOptions.html#instance-member-profiling",
    "src/Gisplay/GisplayOptions.js~GisplayOptions#profiling",
    "member"
  ],
  [
    "src/gisplay/gisplayoptions.js~gisplayoptions#showlegend",
    "class/src/Gisplay/GisplayOptions.js~GisplayOptions.html#instance-member-showLegend",
    "src/Gisplay/GisplayOptions.js~GisplayOptions#showLegend",
    "member"
  ],
  [
    "src/gisplay/gisplayoptions.js~gisplayoptions#showloader",
    "class/src/Gisplay/GisplayOptions.js~GisplayOptions.html#instance-member-showLoader",
    "src/Gisplay/GisplayOptions.js~GisplayOptions#showLoader",
    "member"
  ],
  [
    "src/gisplay/gisplayoptions.js~gisplayoptions#showpropertiesonclick",
    "class/src/Gisplay/GisplayOptions.js~GisplayOptions.html#instance-member-showPropertiesOnClick",
    "src/Gisplay/GisplayOptions.js~GisplayOptions#showPropertiesOnClick",
    "member"
  ],
  [
    "src/gisplay/gisplayoptions.js~gisplayoptions#sizebyclass",
    "class/src/Gisplay/GisplayOptions.js~GisplayOptions.html#instance-member-sizeByClass",
    "src/Gisplay/GisplayOptions.js~GisplayOptions#sizeByClass",
    "member"
  ],
  [
    "src/gisplay/gisplayoptions.js~gisplayoptions#subtrahend",
    "class/src/Gisplay/GisplayOptions.js~GisplayOptions.html#instance-member-subtrahend",
    "src/Gisplay/GisplayOptions.js~GisplayOptions#subtrahend",
    "member"
  ],
  [
    "src/gisplay/gisplayoptions.js~gisplayoptions#usecustommapservice",
    "class/src/Gisplay/GisplayOptions.js~GisplayOptions.html#instance-member-useCustomMapService",
    "src/Gisplay/GisplayOptions.js~GisplayOptions#useCustomMapService",
    "member"
  ],
  [
    "src/gisplay/maps/aesthetic.js",
    "file/src/Gisplay/Maps/Aesthetic.js.html",
    "src/Gisplay/Maps/Aesthetic.js",
    "file"
  ],
  [
    "src/gisplay/maps/aesthetic.js~aesthetic#_allfeatures",
    "class/src/Gisplay/Maps/Aesthetic.js~Aesthetic.html#instance-member-_allFeatures",
    "src/Gisplay/Maps/Aesthetic.js~Aesthetic#_allFeatures",
    "member"
  ],
  [
    "src/gisplay/maps/aesthetic.js~aesthetic#_attr",
    "class/src/Gisplay/Maps/Aesthetic.js~Aesthetic.html#instance-member-_attr",
    "src/Gisplay/Maps/Aesthetic.js~Aesthetic#_attr",
    "member"
  ],
  [
    "src/gisplay/maps/aesthetic.js~aesthetic#_features",
    "class/src/Gisplay/Maps/Aesthetic.js~Aesthetic.html#instance-member-_features",
    "src/Gisplay/Maps/Aesthetic.js~Aesthetic#_features",
    "member"
  ],
  [
    "src/gisplay/maps/aesthetic.js~aesthetic#addfeature",
    "class/src/Gisplay/Maps/Aesthetic.js~Aesthetic.html#instance-method-addFeature",
    "src/Gisplay/Maps/Aesthetic.js~Aesthetic#addFeature",
    "method"
  ],
  [
    "src/gisplay/maps/aesthetic.js~aesthetic#addgroupedfeature",
    "class/src/Gisplay/Maps/Aesthetic.js~Aesthetic.html#instance-method-addGroupedFeature",
    "src/Gisplay/Maps/Aesthetic.js~Aesthetic#addGroupedFeature",
    "method"
  ],
  [
    "src/gisplay/maps/aesthetic.js~aesthetic#checkproperty",
    "class/src/Gisplay/Maps/Aesthetic.js~Aesthetic.html#instance-method-checkProperty",
    "src/Gisplay/Maps/Aesthetic.js~Aesthetic#checkProperty",
    "method"
  ],
  [
    "src/gisplay/maps/aesthetic.js~aesthetic#constructor",
    "class/src/Gisplay/Maps/Aesthetic.js~Aesthetic.html#instance-constructor-constructor",
    "src/Gisplay/Maps/Aesthetic.js~Aesthetic#constructor",
    "method"
  ],
  [
    "src/gisplay/maps/aesthetic.js~aesthetic#enabledisable",
    "class/src/Gisplay/Maps/Aesthetic.js~Aesthetic.html#instance-method-enableDisable",
    "src/Gisplay/Maps/Aesthetic.js~Aesthetic#enableDisable",
    "method"
  ],
  [
    "src/gisplay/maps/aesthetic.js~aesthetic#enabled",
    "class/src/Gisplay/Maps/Aesthetic.js~Aesthetic.html#instance-member-enabled",
    "src/Gisplay/Maps/Aesthetic.js~Aesthetic#enabled",
    "member"
  ],
  [
    "src/gisplay/maps/aesthetic.js~aesthetic#fillcolor",
    "class/src/Gisplay/Maps/Aesthetic.js~Aesthetic.html#instance-member-fillColor",
    "src/Gisplay/Maps/Aesthetic.js~Aesthetic#fillColor",
    "member"
  ],
  [
    "src/gisplay/maps/aesthetic.js~aesthetic#getallfeatures",
    "class/src/Gisplay/Maps/Aesthetic.js~Aesthetic.html#instance-method-getAllFeatures",
    "src/Gisplay/Maps/Aesthetic.js~Aesthetic#getAllFeatures",
    "method"
  ],
  [
    "src/gisplay/maps/aesthetic.js~aesthetic#getattr",
    "class/src/Gisplay/Maps/Aesthetic.js~Aesthetic.html#instance-method-getAttr",
    "src/Gisplay/Maps/Aesthetic.js~Aesthetic#getAttr",
    "method"
  ],
  [
    "src/gisplay/maps/aesthetic.js~aesthetic#getfeatures",
    "class/src/Gisplay/Maps/Aesthetic.js~Aesthetic.html#instance-method-getFeatures",
    "src/Gisplay/Maps/Aesthetic.js~Aesthetic#getFeatures",
    "method"
  ],
  [
    "src/gisplay/maps/aesthetic.js~aesthetic#getfillcolor",
    "class/src/Gisplay/Maps/Aesthetic.js~Aesthetic.html#instance-method-getFillColor",
    "src/Gisplay/Maps/Aesthetic.js~Aesthetic#getFillColor",
    "method"
  ],
  [
    "src/gisplay/maps/aesthetic.js~aesthetic#getpointsize",
    "class/src/Gisplay/Maps/Aesthetic.js~Aesthetic.html#instance-method-getPointSize",
    "src/Gisplay/Maps/Aesthetic.js~Aesthetic#getPointSize",
    "method"
  ],
  [
    "src/gisplay/maps/aesthetic.js~aesthetic#getstrokecolor",
    "class/src/Gisplay/Maps/Aesthetic.js~Aesthetic.html#instance-method-getStrokeColor",
    "src/Gisplay/Maps/Aesthetic.js~Aesthetic#getStrokeColor",
    "method"
  ],
  [
    "src/gisplay/maps/aesthetic.js~aesthetic#id",
    "class/src/Gisplay/Maps/Aesthetic.js~Aesthetic.html#instance-member-id",
    "src/Gisplay/Maps/Aesthetic.js~Aesthetic#id",
    "member"
  ],
  [
    "src/gisplay/maps/aesthetic.js~aesthetic#isenabled",
    "class/src/Gisplay/Maps/Aesthetic.js~Aesthetic.html#instance-method-isEnabled",
    "src/Gisplay/Maps/Aesthetic.js~Aesthetic#isEnabled",
    "method"
  ],
  [
    "src/gisplay/maps/aesthetic.js~aesthetic#isouter",
    "class/src/Gisplay/Maps/Aesthetic.js~Aesthetic.html#instance-method-isOuter",
    "src/Gisplay/Maps/Aesthetic.js~Aesthetic#isOuter",
    "method"
  ],
  [
    "src/gisplay/maps/aesthetic.js~aesthetic#outer",
    "class/src/Gisplay/Maps/Aesthetic.js~Aesthetic.html#instance-member-outer",
    "src/Gisplay/Maps/Aesthetic.js~Aesthetic#outer",
    "member"
  ],
  [
    "src/gisplay/maps/aesthetic.js~aesthetic#pointsize",
    "class/src/Gisplay/Maps/Aesthetic.js~Aesthetic.html#instance-member-pointSize",
    "src/Gisplay/Maps/Aesthetic.js~Aesthetic#pointSize",
    "member"
  ],
  [
    "src/gisplay/maps/aesthetic.js~aesthetic#range",
    "class/src/Gisplay/Maps/Aesthetic.js~Aesthetic.html#instance-member-range",
    "src/Gisplay/Maps/Aesthetic.js~Aesthetic#range",
    "member"
  ],
  [
    "src/gisplay/maps/aesthetic.js~aesthetic#strokecolor",
    "class/src/Gisplay/Maps/Aesthetic.js~Aesthetic.html#instance-member-strokeColor",
    "src/Gisplay/Maps/Aesthetic.js~Aesthetic#strokeColor",
    "member"
  ],
  [
    "src/gisplay/maps/bgmapwrapper.js",
    "file/src/Gisplay/Maps/BGMapWrapper.js.html",
    "src/Gisplay/Maps/BGMapWrapper.js",
    "file"
  ],
  [
    "src/gisplay/maps/bgmapwrapper.js~bgmapwrapper#bgmapobject",
    "class/src/Gisplay/Maps/BGMapWrapper.js~BGMapWrapper.html#instance-member-bgMapObject",
    "src/Gisplay/Maps/BGMapWrapper.js~BGMapWrapper#bgMapObject",
    "member"
  ],
  [
    "src/gisplay/maps/bgmapwrapper.js~bgmapwrapper#constructor",
    "class/src/Gisplay/Maps/BGMapWrapper.js~BGMapWrapper.html#instance-constructor-constructor",
    "src/Gisplay/Maps/BGMapWrapper.js~BGMapWrapper#constructor",
    "method"
  ],
  [
    "src/gisplay/maps/bgmapwrapper.js~bgmapwrapper#createcanvas",
    "class/src/Gisplay/Maps/BGMapWrapper.js~BGMapWrapper.html#instance-method-createCanvas",
    "src/Gisplay/Maps/BGMapWrapper.js~BGMapWrapper#createCanvas",
    "method"
  ],
  [
    "src/gisplay/maps/bgmapwrapper.js~bgmapwrapper#createloader",
    "class/src/Gisplay/Maps/BGMapWrapper.js~BGMapWrapper.html#instance-method-createLoader",
    "src/Gisplay/Maps/BGMapWrapper.js~BGMapWrapper#createLoader",
    "method"
  ],
  [
    "src/gisplay/maps/bgmapwrapper.js~bgmapwrapper#getcontainer",
    "class/src/Gisplay/Maps/BGMapWrapper.js~BGMapWrapper.html#instance-method-getContainer",
    "src/Gisplay/Maps/BGMapWrapper.js~BGMapWrapper#getContainer",
    "method"
  ],
  [
    "src/gisplay/maps/bgmapwrapper.js~bgmapwrapper#getlatbound",
    "class/src/Gisplay/Maps/BGMapWrapper.js~BGMapWrapper.html#instance-method-getLatBound",
    "src/Gisplay/Maps/BGMapWrapper.js~BGMapWrapper#getLatBound",
    "method"
  ],
  [
    "src/gisplay/maps/bgmapwrapper.js~bgmapwrapper#getlngbound",
    "class/src/Gisplay/Maps/BGMapWrapper.js~BGMapWrapper.html#instance-method-getLngBound",
    "src/Gisplay/Maps/BGMapWrapper.js~BGMapWrapper#getLngBound",
    "method"
  ],
  [
    "src/gisplay/maps/bgmapwrapper.js~bgmapwrapper#getzoom",
    "class/src/Gisplay/Maps/BGMapWrapper.js~BGMapWrapper.html#instance-method-getZoom",
    "src/Gisplay/Maps/BGMapWrapper.js~BGMapWrapper#getZoom",
    "method"
  ],
  [
    "src/gisplay/maps/bgmapwrapper.js~bgmapwrapper#loaderdiv",
    "class/src/Gisplay/Maps/BGMapWrapper.js~BGMapWrapper.html#instance-member-loaderDiv",
    "src/Gisplay/Maps/BGMapWrapper.js~BGMapWrapper#loaderDiv",
    "member"
  ],
  [
    "src/gisplay/maps/bgmapwrapper.js~bgmapwrapper#onevent",
    "class/src/Gisplay/Maps/BGMapWrapper.js~BGMapWrapper.html#instance-method-onEvent",
    "src/Gisplay/Maps/BGMapWrapper.js~BGMapWrapper#onEvent",
    "method"
  ],
  [
    "src/gisplay/maps/bgmapwrapper.js~bgmapwrapper#showloader",
    "class/src/Gisplay/Maps/BGMapWrapper.js~BGMapWrapper.html#instance-method-showLoader",
    "src/Gisplay/Maps/BGMapWrapper.js~BGMapWrapper#showLoader",
    "method"
  ],
  [
    "src/gisplay/maps/feature.js",
    "file/src/Gisplay/Maps/Feature.js.html",
    "src/Gisplay/Maps/Feature.js",
    "file"
  ],
  [
    "src/gisplay/maps/feature.js~feature#_borders",
    "class/src/Gisplay/Maps/Feature.js~Feature.html#instance-member-_borders",
    "src/Gisplay/Maps/Feature.js~Feature#_borders",
    "member"
  ],
  [
    "src/gisplay/maps/feature.js~feature#_id",
    "class/src/Gisplay/Maps/Feature.js~Feature.html#instance-member-_id",
    "src/Gisplay/Maps/Feature.js~Feature#_id",
    "member"
  ],
  [
    "src/gisplay/maps/feature.js~feature#_points",
    "class/src/Gisplay/Maps/Feature.js~Feature.html#instance-member-_points",
    "src/Gisplay/Maps/Feature.js~Feature#_points",
    "member"
  ],
  [
    "src/gisplay/maps/feature.js~feature#_properties",
    "class/src/Gisplay/Maps/Feature.js~Feature.html#instance-member-_properties",
    "src/Gisplay/Maps/Feature.js~Feature#_properties",
    "member"
  ],
  [
    "src/gisplay/maps/feature.js~feature#_triangles",
    "class/src/Gisplay/Maps/Feature.js~Feature.html#instance-member-_triangles",
    "src/Gisplay/Maps/Feature.js~Feature#_triangles",
    "member"
  ],
  [
    "src/gisplay/maps/feature.js~feature#constructor",
    "class/src/Gisplay/Maps/Feature.js~Feature.html#instance-constructor-constructor",
    "src/Gisplay/Maps/Feature.js~Feature#constructor",
    "method"
  ],
  [
    "src/gisplay/maps/feature.js~feature#getborders",
    "class/src/Gisplay/Maps/Feature.js~Feature.html#instance-method-getBorders",
    "src/Gisplay/Maps/Feature.js~Feature#getBorders",
    "method"
  ],
  [
    "src/gisplay/maps/feature.js~feature#getpoints",
    "class/src/Gisplay/Maps/Feature.js~Feature.html#instance-method-getPoints",
    "src/Gisplay/Maps/Feature.js~Feature#getPoints",
    "method"
  ],
  [
    "src/gisplay/maps/feature.js~feature#getproperties",
    "class/src/Gisplay/Maps/Feature.js~Feature.html#instance-method-getProperties",
    "src/Gisplay/Maps/Feature.js~Feature#getProperties",
    "method"
  ],
  [
    "src/gisplay/maps/feature.js~feature#gettriangles",
    "class/src/Gisplay/Maps/Feature.js~Feature.html#instance-method-getTriangles",
    "src/Gisplay/Maps/Feature.js~Feature#getTriangles",
    "method"
  ],
  [
    "src/gisplay/maps/legend.js",
    "file/src/Gisplay/Maps/Legend.js.html",
    "src/Gisplay/Maps/Legend.js",
    "file"
  ],
  [
    "src/gisplay/maps/legend.js~legend#point",
    "class/src/Gisplay/Maps/Legend.js~Legend.html#instance-member-POINT",
    "src/Gisplay/Maps/Legend.js~Legend#POINT",
    "member"
  ],
  [
    "src/gisplay/maps/legend.js~legend#polygon",
    "class/src/Gisplay/Maps/Legend.js~Legend.html#instance-member-POLYGON",
    "src/Gisplay/Maps/Legend.js~Legend#POLYGON",
    "member"
  ],
  [
    "src/gisplay/maps/legend.js~legend#classname",
    "class/src/Gisplay/Maps/Legend.js~Legend.html#instance-member-className",
    "src/Gisplay/Maps/Legend.js~Legend#className",
    "member"
  ],
  [
    "src/gisplay/maps/legend.js~legend#constructor",
    "class/src/Gisplay/Maps/Legend.js~Legend.html#instance-constructor-constructor",
    "src/Gisplay/Maps/Legend.js~Legend#constructor",
    "method"
  ],
  [
    "src/gisplay/maps/legend.js~legend#firstinsertion",
    "class/src/Gisplay/Maps/Legend.js~Legend.html#instance-member-firstInsertion",
    "src/Gisplay/Maps/Legend.js~Legend#firstInsertion",
    "member"
  ],
  [
    "src/gisplay/maps/legend.js~legend#init",
    "class/src/Gisplay/Maps/Legend.js~Legend.html#instance-method-init",
    "src/Gisplay/Maps/Legend.js~Legend#init",
    "method"
  ],
  [
    "src/gisplay/maps/legend.js~legend#insertgradient",
    "class/src/Gisplay/Maps/Legend.js~Legend.html#instance-method-insertGradient",
    "src/Gisplay/Maps/Legend.js~Legend#insertGradient",
    "method"
  ],
  [
    "src/gisplay/maps/legend.js~legend#insertlegend",
    "class/src/Gisplay/Maps/Legend.js~Legend.html#instance-method-insertLegend",
    "src/Gisplay/Maps/Legend.js~Legend#insertLegend",
    "method"
  ],
  [
    "src/gisplay/maps/legend.js~legend#insertpointrow",
    "class/src/Gisplay/Maps/Legend.js~Legend.html#instance-method-insertPointRow",
    "src/Gisplay/Maps/Legend.js~Legend#insertPointRow",
    "method"
  ],
  [
    "src/gisplay/maps/legend.js~legend#insertpolygonrow",
    "class/src/Gisplay/Maps/Legend.js~Legend.html#instance-method-insertPolygonRow",
    "src/Gisplay/Maps/Legend.js~Legend#insertPolygonRow",
    "method"
  ],
  [
    "src/gisplay/maps/legend.js~legend#insertproportionalsymbols",
    "class/src/Gisplay/Maps/Legend.js~Legend.html#instance-method-insertProportionalSymbols",
    "src/Gisplay/Maps/Legend.js~Legend#insertProportionalSymbols",
    "method"
  ],
  [
    "src/gisplay/maps/legend.js~legend#insertrow",
    "class/src/Gisplay/Maps/Legend.js~Legend.html#instance-method-insertRow",
    "src/Gisplay/Maps/Legend.js~Legend#insertRow",
    "method"
  ],
  [
    "src/gisplay/maps/legend.js~legend#lastdiv",
    "class/src/Gisplay/Maps/Legend.js~Legend.html#instance-member-lastdiv",
    "src/Gisplay/Maps/Legend.js~Legend#lastdiv",
    "member"
  ],
  [
    "src/gisplay/maps/legend.js~legend#legenddiv",
    "class/src/Gisplay/Maps/Legend.js~Legend.html#instance-member-legendDiv",
    "src/Gisplay/Maps/Legend.js~Legend#legendDiv",
    "member"
  ],
  [
    "src/gisplay/maps/legend.js~legend#table",
    "class/src/Gisplay/Maps/Legend.js~Legend.html#instance-member-table",
    "src/Gisplay/Maps/Legend.js~Legend#table",
    "member"
  ],
  [
    "src/gisplay/maps/legend.js~legend#title",
    "class/src/Gisplay/Maps/Legend.js~Legend.html#instance-member-title",
    "src/Gisplay/Maps/Legend.js~Legend#title",
    "member"
  ],
  [
    "src/gisplay/maps/map.js",
    "file/src/Gisplay/Maps/Map.js.html",
    "src/Gisplay/Maps/Map.js",
    "file"
  ],
  [
    "src/gisplay/maps/map.js~map#_webgl",
    "class/src/Gisplay/Maps/Map.js~Map.html#instance-member-_webgl",
    "src/Gisplay/Maps/Map.js~Map#_webgl",
    "member"
  ],
  [
    "src/gisplay/maps/map.js~map#aesthetics",
    "class/src/Gisplay/Maps/Map.js~Map.html#instance-member-aesthetics",
    "src/Gisplay/Maps/Map.js~Map#aesthetics",
    "member"
  ],
  [
    "src/gisplay/maps/map.js~map#bgmap",
    "class/src/Gisplay/Maps/Map.js~Map.html#instance-member-bGMap",
    "src/Gisplay/Maps/Map.js~Map#bGMap",
    "member"
  ],
  [
    "src/gisplay/maps/map.js~map#buildlegend",
    "class/src/Gisplay/Maps/Map.js~Map.html#instance-method-buildLegend",
    "src/Gisplay/Maps/Map.js~Map#buildLegend",
    "method"
  ],
  [
    "src/gisplay/maps/map.js~map#buildtrees",
    "class/src/Gisplay/Maps/Map.js~Map.html#instance-method-buildTrees",
    "src/Gisplay/Maps/Map.js~Map#buildTrees",
    "method"
  ],
  [
    "src/gisplay/maps/map.js~map#calcclassbreaks",
    "class/src/Gisplay/Maps/Map.js~Map.html#instance-method-calcClassBreaks",
    "src/Gisplay/Maps/Map.js~Map#calcClassBreaks",
    "method"
  ],
  [
    "src/gisplay/maps/map.js~map#clear",
    "class/src/Gisplay/Maps/Map.js~Map.html#instance-method-clear",
    "src/Gisplay/Maps/Map.js~Map#clear",
    "method"
  ],
  [
    "src/gisplay/maps/map.js~map#constructor",
    "class/src/Gisplay/Maps/Map.js~Map.html#instance-constructor-constructor",
    "src/Gisplay/Maps/Map.js~Map#constructor",
    "method"
  ],
  [
    "src/gisplay/maps/map.js~map#createandcompileshader",
    "class/src/Gisplay/Maps/Map.js~Map.html#instance-method-createAndCompileShader",
    "src/Gisplay/Maps/Map.js~Map#createAndCompileShader",
    "method"
  ],
  [
    "src/gisplay/maps/map.js~map#createandinsertfeature",
    "class/src/Gisplay/Maps/Map.js~Map.html#instance-method-createAndInsertFeature",
    "src/Gisplay/Maps/Map.js~Map#createAndInsertFeature",
    "method"
  ],
  [
    "src/gisplay/maps/map.js~map#createcanvas",
    "class/src/Gisplay/Maps/Map.js~Map.html#instance-method-createCanvas",
    "src/Gisplay/Maps/Map.js~Map#createCanvas",
    "method"
  ],
  [
    "src/gisplay/maps/map.js~map#defaults",
    "class/src/Gisplay/Maps/Map.js~Map.html#instance-method-defaults",
    "src/Gisplay/Maps/Map.js~Map#defaults",
    "method"
  ],
  [
    "src/gisplay/maps/map.js~map#draw",
    "class/src/Gisplay/Maps/Map.js~Map.html#instance-method-draw",
    "src/Gisplay/Maps/Map.js~Map#draw",
    "method"
  ],
  [
    "src/gisplay/maps/map.js~map#drawborders",
    "class/src/Gisplay/Maps/Map.js~Map.html#instance-method-drawBorders",
    "src/Gisplay/Maps/Map.js~Map#drawBorders",
    "method"
  ],
  [
    "src/gisplay/maps/map.js~map#drawcontinuouspolygons",
    "class/src/Gisplay/Maps/Map.js~Map.html#instance-method-drawContinuousPolygons",
    "src/Gisplay/Maps/Map.js~Map#drawContinuousPolygons",
    "method"
  ],
  [
    "src/gisplay/maps/map.js~map#drawpoints",
    "class/src/Gisplay/Maps/Map.js~Map.html#instance-method-drawPoints",
    "src/Gisplay/Maps/Map.js~Map#drawPoints",
    "method"
  ],
  [
    "src/gisplay/maps/map.js~map#drawproportionalpoints",
    "class/src/Gisplay/Maps/Map.js~Map.html#instance-method-drawProportionalPoints",
    "src/Gisplay/Maps/Map.js~Map#drawProportionalPoints",
    "method"
  ],
  [
    "src/gisplay/maps/map.js~map#drawtriangles",
    "class/src/Gisplay/Maps/Map.js~Map.html#instance-method-drawTriangles",
    "src/Gisplay/Maps/Map.js~Map#drawTriangles",
    "method"
  ],
  [
    "src/gisplay/maps/map.js~map#fitfeature",
    "class/src/Gisplay/Maps/Map.js~Map.html#instance-method-fitFeature",
    "src/Gisplay/Maps/Map.js~Map#fitFeature",
    "method"
  ],
  [
    "src/gisplay/maps/map.js~map#generateshaderssourcecode",
    "class/src/Gisplay/Maps/Map.js~Map.html#instance-method-generateShadersSourceCode",
    "src/Gisplay/Maps/Map.js~Map#generateShadersSourceCode",
    "method"
  ],
  [
    "src/gisplay/maps/map.js~map#geometry",
    "class/src/Gisplay/Maps/Map.js~Map.html#instance-member-geometry",
    "src/Gisplay/Maps/Map.js~Map#geometry",
    "member"
  ],
  [
    "src/gisplay/maps/map.js~map#gisplayoptions",
    "class/src/Gisplay/Maps/Map.js~Map.html#instance-member-gisplayOptions",
    "src/Gisplay/Maps/Map.js~Map#gisplayOptions",
    "member"
  ],
  [
    "src/gisplay/maps/map.js~map#haspolygons",
    "class/src/Gisplay/Maps/Map.js~Map.html#instance-member-hasPolygons",
    "src/Gisplay/Maps/Map.js~Map#hasPolygons",
    "member"
  ],
  [
    "src/gisplay/maps/map.js~map#id",
    "class/src/Gisplay/Maps/Map.js~Map.html#instance-member-id",
    "src/Gisplay/Maps/Map.js~Map#id",
    "member"
  ],
  [
    "src/gisplay/maps/map.js~map#initialize",
    "class/src/Gisplay/Maps/Map.js~Map.html#instance-method-initialize",
    "src/Gisplay/Maps/Map.js~Map#initialize",
    "method"
  ],
  [
    "src/gisplay/maps/map.js~map#insertfeature",
    "class/src/Gisplay/Maps/Map.js~Map.html#instance-method-insertFeature",
    "src/Gisplay/Maps/Map.js~Map#insertFeature",
    "method"
  ],
  [
    "src/gisplay/maps/map.js~map#insertgroupedfeature",
    "class/src/Gisplay/Maps/Map.js~Map.html#instance-method-insertGroupedFeature",
    "src/Gisplay/Maps/Map.js~Map#insertGroupedFeature",
    "method"
  ],
  [
    "src/gisplay/maps/map.js~map#kdtree",
    "class/src/Gisplay/Maps/Map.js~Map.html#instance-member-kdtree",
    "src/Gisplay/Maps/Map.js~Map#kdtree",
    "member"
  ],
  [
    "src/gisplay/maps/map.js~map#latlongtopixelxy",
    "class/src/Gisplay/Maps/Map.js~Map.html#instance-method-latLongToPixelXY",
    "src/Gisplay/Maps/Map.js~Map#latLongToPixelXY",
    "method"
  ],
  [
    "src/gisplay/maps/map.js~map#loadgeojson",
    "class/src/Gisplay/Maps/Map.js~Map.html#instance-method-loadGeoJSON",
    "src/Gisplay/Maps/Map.js~Map#loadGeoJSON",
    "method"
  ],
  [
    "src/gisplay/maps/map.js~map#loadoptions",
    "class/src/Gisplay/Maps/Map.js~Map.html#instance-method-loadOptions",
    "src/Gisplay/Maps/Map.js~Map#loadOptions",
    "method"
  ],
  [
    "src/gisplay/maps/map.js~map#makemap",
    "class/src/Gisplay/Maps/Map.js~Map.html#instance-method-makeMap",
    "src/Gisplay/Maps/Map.js~Map#makeMap",
    "method"
  ],
  [
    "src/gisplay/maps/map.js~map#max",
    "class/src/Gisplay/Maps/Map.js~Map.html#instance-member-max",
    "src/Gisplay/Maps/Map.js~Map#max",
    "member"
  ],
  [
    "src/gisplay/maps/map.js~map#min",
    "class/src/Gisplay/Maps/Map.js~Map.html#instance-member-min",
    "src/Gisplay/Maps/Map.js~Map#min",
    "member"
  ],
  [
    "src/gisplay/maps/map.js~map#preprocessdata",
    "class/src/Gisplay/Maps/Map.js~Map.html#instance-method-preProcessData",
    "src/Gisplay/Maps/Map.js~Map#preProcessData",
    "method"
  ],
  [
    "src/gisplay/maps/map.js~map#processdata",
    "class/src/Gisplay/Maps/Map.js~Map.html#instance-method-processData",
    "src/Gisplay/Maps/Map.js~Map#processData",
    "method"
  ],
  [
    "src/gisplay/maps/map.js~map#processpolygon",
    "class/src/Gisplay/Maps/Map.js~Map.html#instance-method-processPolygon",
    "src/Gisplay/Maps/Map.js~Map#processPolygon",
    "method"
  ],
  [
    "src/gisplay/maps/map.js~map#program",
    "class/src/Gisplay/Maps/Map.js~Map.html#instance-method-program",
    "src/Gisplay/Maps/Map.js~Map#program",
    "method"
  ],
  [
    "src/gisplay/maps/map.js~map#rtree",
    "class/src/Gisplay/Maps/Map.js~Map.html#instance-member-rtree",
    "src/Gisplay/Maps/Map.js~Map#rtree",
    "member"
  ],
  [
    "src/gisplay/maps/map.js~map#scaleprojection",
    "class/src/Gisplay/Maps/Map.js~Map.html#instance-method-scaleProjection",
    "src/Gisplay/Maps/Map.js~Map#scaleProjection",
    "method"
  ],
  [
    "src/gisplay/maps/map.js~map#setupfunctiononclick",
    "class/src/Gisplay/Maps/Map.js~Map.html#instance-method-setupFunctionOnclick",
    "src/Gisplay/Maps/Map.js~Map#setupFunctionOnclick",
    "method"
  ],
  [
    "src/gisplay/maps/map.js~map#showloader",
    "class/src/Gisplay/Maps/Map.js~Map.html#instance-method-showLoader",
    "src/Gisplay/Maps/Map.js~Map#showLoader",
    "method"
  ],
  [
    "src/gisplay/maps/map.js~map#tempaestheticpoints",
    "class/src/Gisplay/Maps/Map.js~Map.html#instance-member-tempAestheticPoints",
    "src/Gisplay/Maps/Map.js~Map#tempAestheticPoints",
    "member"
  ],
  [
    "src/gisplay/maps/map.js~map#translateprojection",
    "class/src/Gisplay/Maps/Map.js~Map.html#instance-method-translateProjection",
    "src/Gisplay/Maps/Map.js~Map#translateProjection",
    "method"
  ],
  [
    "src/gisplay/maps/map.js~map#treepoints",
    "class/src/Gisplay/Maps/Map.js~Map.html#instance-member-treepoints",
    "src/Gisplay/Maps/Map.js~Map#treepoints",
    "member"
  ],
  [
    "src/gisplay/maps/types/changemap.js",
    "file/src/Gisplay/Maps/Types/ChangeMap.js.html",
    "src/Gisplay/Maps/Types/ChangeMap.js",
    "file"
  ],
  [
    "src/gisplay/maps/types/changemap.js~changemap#aesthetics",
    "class/src/Gisplay/Maps/Types/ChangeMap.js~ChangeMap.html#instance-member-aesthetics",
    "src/Gisplay/Maps/Types/ChangeMap.js~ChangeMap#aesthetics",
    "member"
  ],
  [
    "src/gisplay/maps/types/changemap.js~changemap#buildlegend",
    "class/src/Gisplay/Maps/Types/ChangeMap.js~ChangeMap.html#instance-method-buildLegend",
    "src/Gisplay/Maps/Types/ChangeMap.js~ChangeMap#buildLegend",
    "method"
  ],
  [
    "src/gisplay/maps/types/changemap.js~changemap#constructor",
    "class/src/Gisplay/Maps/Types/ChangeMap.js~ChangeMap.html#instance-constructor-constructor",
    "src/Gisplay/Maps/Types/ChangeMap.js~ChangeMap#constructor",
    "method"
  ],
  [
    "src/gisplay/maps/types/changemap.js~changemap#defaults",
    "class/src/Gisplay/Maps/Types/ChangeMap.js~ChangeMap.html#instance-method-defaults",
    "src/Gisplay/Maps/Types/ChangeMap.js~ChangeMap#defaults",
    "method"
  ],
  [
    "src/gisplay/maps/types/changemap.js~changemap#draw",
    "class/src/Gisplay/Maps/Types/ChangeMap.js~ChangeMap.html#instance-method-draw",
    "src/Gisplay/Maps/Types/ChangeMap.js~ChangeMap#draw",
    "method"
  ],
  [
    "src/gisplay/maps/types/changemap.js~changemap#fcolor",
    "class/src/Gisplay/Maps/Types/ChangeMap.js~ChangeMap.html#instance-member-fcolor",
    "src/Gisplay/Maps/Types/ChangeMap.js~ChangeMap#fcolor",
    "member"
  ],
  [
    "src/gisplay/maps/types/changemap.js~changemap#legend",
    "class/src/Gisplay/Maps/Types/ChangeMap.js~ChangeMap.html#instance-member-legend",
    "src/Gisplay/Maps/Types/ChangeMap.js~ChangeMap#legend",
    "member"
  ],
  [
    "src/gisplay/maps/types/changemap.js~changemap#max",
    "class/src/Gisplay/Maps/Types/ChangeMap.js~ChangeMap.html#instance-member-max",
    "src/Gisplay/Maps/Types/ChangeMap.js~ChangeMap#max",
    "member"
  ],
  [
    "src/gisplay/maps/types/changemap.js~changemap#min",
    "class/src/Gisplay/Maps/Types/ChangeMap.js~ChangeMap.html#instance-member-min",
    "src/Gisplay/Maps/Types/ChangeMap.js~ChangeMap#min",
    "member"
  ],
  [
    "src/gisplay/maps/types/changemap.js~changemap#preprocessdata",
    "class/src/Gisplay/Maps/Types/ChangeMap.js~ChangeMap.html#instance-method-preProcessData",
    "src/Gisplay/Maps/Types/ChangeMap.js~ChangeMap#preProcessData",
    "method"
  ],
  [
    "src/gisplay/maps/types/chorochromaticmap.js",
    "file/src/Gisplay/Maps/Types/ChorochromaticMap.js.html",
    "src/Gisplay/Maps/Types/ChorochromaticMap.js",
    "file"
  ],
  [
    "src/gisplay/maps/types/chorochromaticmap.js~chorochromaticmap#constructor",
    "class/src/Gisplay/Maps/Types/ChorochromaticMap.js~ChorochromaticMap.html#instance-constructor-constructor",
    "src/Gisplay/Maps/Types/ChorochromaticMap.js~ChorochromaticMap#constructor",
    "method"
  ],
  [
    "src/gisplay/maps/types/chorochromaticmap.js~chorochromaticmap#defaults",
    "class/src/Gisplay/Maps/Types/ChorochromaticMap.js~ChorochromaticMap.html#instance-method-defaults",
    "src/Gisplay/Maps/Types/ChorochromaticMap.js~ChorochromaticMap#defaults",
    "method"
  ],
  [
    "src/gisplay/maps/types/choropleth.js",
    "file/src/Gisplay/Maps/Types/Choropleth.js.html",
    "src/Gisplay/Maps/Types/Choropleth.js",
    "file"
  ],
  [
    "src/gisplay/maps/types/choropleth.js~choropleth#buildlegend",
    "class/src/Gisplay/Maps/Types/Choropleth.js~Choropleth.html#instance-method-buildLegend",
    "src/Gisplay/Maps/Types/Choropleth.js~Choropleth#buildLegend",
    "method"
  ],
  [
    "src/gisplay/maps/types/choropleth.js~choropleth#constructor",
    "class/src/Gisplay/Maps/Types/Choropleth.js~Choropleth.html#instance-constructor-constructor",
    "src/Gisplay/Maps/Types/Choropleth.js~Choropleth#constructor",
    "method"
  ],
  [
    "src/gisplay/maps/types/choropleth.js~choropleth#defaults",
    "class/src/Gisplay/Maps/Types/Choropleth.js~Choropleth.html#instance-method-defaults",
    "src/Gisplay/Maps/Types/Choropleth.js~Choropleth#defaults",
    "method"
  ],
  [
    "src/gisplay/maps/types/choropleth.js~choropleth#draw",
    "class/src/Gisplay/Maps/Types/Choropleth.js~Choropleth.html#instance-method-draw",
    "src/Gisplay/Maps/Types/Choropleth.js~Choropleth#draw",
    "method"
  ],
  [
    "src/gisplay/maps/types/choropleth.js~choropleth#legend",
    "class/src/Gisplay/Maps/Types/Choropleth.js~Choropleth.html#instance-member-legend",
    "src/Gisplay/Maps/Types/Choropleth.js~Choropleth#legend",
    "member"
  ],
  [
    "src/gisplay/maps/types/dotmap.js",
    "file/src/Gisplay/Maps/Types/DotMap.js.html",
    "src/Gisplay/Maps/Types/DotMap.js",
    "file"
  ],
  [
    "src/gisplay/maps/types/dotmap.js~dotmap#buildlegend",
    "class/src/Gisplay/Maps/Types/DotMap.js~DotMap.html#instance-method-buildLegend",
    "src/Gisplay/Maps/Types/DotMap.js~DotMap#buildLegend",
    "method"
  ],
  [
    "src/gisplay/maps/types/dotmap.js~dotmap#constructor",
    "class/src/Gisplay/Maps/Types/DotMap.js~DotMap.html#instance-constructor-constructor",
    "src/Gisplay/Maps/Types/DotMap.js~DotMap#constructor",
    "method"
  ],
  [
    "src/gisplay/maps/types/dotmap.js~dotmap#defaults",
    "class/src/Gisplay/Maps/Types/DotMap.js~DotMap.html#instance-method-defaults",
    "src/Gisplay/Maps/Types/DotMap.js~DotMap#defaults",
    "method"
  ],
  [
    "src/gisplay/maps/types/dotmap.js~dotmap#draw",
    "class/src/Gisplay/Maps/Types/DotMap.js~DotMap.html#instance-method-draw",
    "src/Gisplay/Maps/Types/DotMap.js~DotMap#draw",
    "method"
  ],
  [
    "src/gisplay/maps/types/dotmap.js~dotmap#legend",
    "class/src/Gisplay/Maps/Types/DotMap.js~DotMap.html#instance-member-legend",
    "src/Gisplay/Maps/Types/DotMap.js~DotMap#legend",
    "member"
  ],
  [
    "src/gisplay/maps/types/proportionalsymbolsmap.js",
    "file/src/Gisplay/Maps/Types/ProportionalSymbolsMap.js.html",
    "src/Gisplay/Maps/Types/ProportionalSymbolsMap.js",
    "file"
  ],
  [
    "src/gisplay/maps/types/proportionalsymbolsmap.js~proportionalsymbolsmap#buildlegend",
    "class/src/Gisplay/Maps/Types/ProportionalSymbolsMap.js~ProportionalSymbolsMap.html#instance-method-buildLegend",
    "src/Gisplay/Maps/Types/ProportionalSymbolsMap.js~ProportionalSymbolsMap#buildLegend",
    "method"
  ],
  [
    "src/gisplay/maps/types/proportionalsymbolsmap.js~proportionalsymbolsmap#constructor",
    "class/src/Gisplay/Maps/Types/ProportionalSymbolsMap.js~ProportionalSymbolsMap.html#instance-constructor-constructor",
    "src/Gisplay/Maps/Types/ProportionalSymbolsMap.js~ProportionalSymbolsMap#constructor",
    "method"
  ],
  [
    "src/gisplay/maps/types/proportionalsymbolsmap.js~proportionalsymbolsmap#defaults",
    "class/src/Gisplay/Maps/Types/ProportionalSymbolsMap.js~ProportionalSymbolsMap.html#instance-method-defaults",
    "src/Gisplay/Maps/Types/ProportionalSymbolsMap.js~ProportionalSymbolsMap#defaults",
    "method"
  ],
  [
    "src/gisplay/maps/types/proportionalsymbolsmap.js~proportionalsymbolsmap#draw",
    "class/src/Gisplay/Maps/Types/ProportionalSymbolsMap.js~ProportionalSymbolsMap.html#instance-method-draw",
    "src/Gisplay/Maps/Types/ProportionalSymbolsMap.js~ProportionalSymbolsMap#draw",
    "method"
  ],
  [
    "src/gisplay/maps/types/proportionalsymbolsmap.js~proportionalsymbolsmap#legend",
    "class/src/Gisplay/Maps/Types/ProportionalSymbolsMap.js~ProportionalSymbolsMap.html#instance-member-legend",
    "src/Gisplay/Maps/Types/ProportionalSymbolsMap.js~ProportionalSymbolsMap#legend",
    "member"
  ],
  [
    "src/gisplay/maps/v11/choroplethgooglemaps.js",
    "file/src/Gisplay/Maps/v11/ChoroplethGoogleMaps.js.html",
    "src/Gisplay/Maps/v11/ChoroplethGoogleMaps.js",
    "file"
  ],
  [
    "src/gisplay/maps/v11/choroplethgooglemaps.js~choroplethgooglemaps#constructor",
    "class/src/Gisplay/Maps/v11/ChoroplethGoogleMaps.js~ChoroplethGoogleMaps.html#instance-constructor-constructor",
    "src/Gisplay/Maps/v11/ChoroplethGoogleMaps.js~ChoroplethGoogleMaps#constructor",
    "method"
  ],
  [
    "src/gisplay/maps/v11/choroplethgooglemaps.js~choroplethgooglemaps#initialize",
    "class/src/Gisplay/Maps/v11/ChoroplethGoogleMaps.js~ChoroplethGoogleMaps.html#instance-method-initialize",
    "src/Gisplay/Maps/v11/ChoroplethGoogleMaps.js~ChoroplethGoogleMaps#initialize",
    "method"
  ],
  [
    "src/gisplay/maps/v11/choroplethgooglemaps.js~choroplethgooglemaps#setupfunctiononclick",
    "class/src/Gisplay/Maps/v11/ChoroplethGoogleMaps.js~ChoroplethGoogleMaps.html#instance-method-setupFunctionOnclick",
    "src/Gisplay/Maps/v11/ChoroplethGoogleMaps.js~ChoroplethGoogleMaps#setupFunctionOnclick",
    "method"
  ],
  [
    "src/gisplay/maps/v11/googlemapsbgmap.js",
    "file/src/Gisplay/Maps/v11/GoogleMapsBGMap.js.html",
    "src/Gisplay/Maps/v11/GoogleMapsBGMap.js",
    "file"
  ],
  [
    "src/gisplay/maps/v11/googlemapsbgmap.js~googlemapsbgmap#constructor",
    "class/src/Gisplay/Maps/v11/GoogleMapsBGMap.js~GoogleMapsBGMap.html#instance-constructor-constructor",
    "src/Gisplay/Maps/v11/GoogleMapsBGMap.js~GoogleMapsBGMap#constructor",
    "method"
  ],
  [
    "src/gisplay/maps/v11/googlemapsbgmap.js~googlemapsbgmap#createcanvas",
    "class/src/Gisplay/Maps/v11/GoogleMapsBGMap.js~GoogleMapsBGMap.html#instance-method-createCanvas",
    "src/Gisplay/Maps/v11/GoogleMapsBGMap.js~GoogleMapsBGMap#createCanvas",
    "method"
  ],
  [
    "src/gisplay/maps/v11/googlemapsbgmap.js~googlemapsbgmap#getcontainer",
    "class/src/Gisplay/Maps/v11/GoogleMapsBGMap.js~GoogleMapsBGMap.html#instance-method-getContainer",
    "src/Gisplay/Maps/v11/GoogleMapsBGMap.js~GoogleMapsBGMap#getContainer",
    "method"
  ],
  [
    "src/gisplay/maps/v11/googlemapsbgmap.js~googlemapsbgmap#getlatbound",
    "class/src/Gisplay/Maps/v11/GoogleMapsBGMap.js~GoogleMapsBGMap.html#instance-method-getLatBound",
    "src/Gisplay/Maps/v11/GoogleMapsBGMap.js~GoogleMapsBGMap#getLatBound",
    "method"
  ],
  [
    "src/gisplay/maps/v11/googlemapsbgmap.js~googlemapsbgmap#getlngbound",
    "class/src/Gisplay/Maps/v11/GoogleMapsBGMap.js~GoogleMapsBGMap.html#instance-method-getLngBound",
    "src/Gisplay/Maps/v11/GoogleMapsBGMap.js~GoogleMapsBGMap#getLngBound",
    "method"
  ],
  [
    "src/gisplay/maps/v11/googlemapsbgmap.js~googlemapsbgmap#getzoom",
    "class/src/Gisplay/Maps/v11/GoogleMapsBGMap.js~GoogleMapsBGMap.html#instance-method-getZoom",
    "src/Gisplay/Maps/v11/GoogleMapsBGMap.js~GoogleMapsBGMap#getZoom",
    "method"
  ],
  [
    "src/gisplay/maps/v11/googlemapsbgmap.js~googlemapsbgmap#onevent",
    "class/src/Gisplay/Maps/v11/GoogleMapsBGMap.js~GoogleMapsBGMap.html#instance-method-onEvent",
    "src/Gisplay/Maps/v11/GoogleMapsBGMap.js~GoogleMapsBGMap#onEvent",
    "method"
  ],
  [
    "src/gisplayv1.js",
    "file/src/gisplayv1.js.html",
    "src/gisplayv1.js",
    "file"
  ],
  [
    "src/gisplayv11.js",
    "file/src/gisplayv11.js.html",
    "src/gisplayv11.js",
    "file"
  ],
  [
    "src/lib/chroma.min.js",
    "file/src/lib/chroma.min.js.html",
    "src/lib/chroma.min.js",
    "file"
  ],
  [
    "src/lib/earcut.js",
    "file/src/lib/earcut.js.html",
    "src/lib/earcut.js",
    "file"
  ],
  [
    "src/lib/jquery-2.1.4.min.js",
    "file/src/lib/jquery-2.1.4.min.js.html",
    "src/lib/jquery-2.1.4.min.js",
    "file"
  ],
  [
    "src/lib/kdtree.js",
    "file/src/lib/kdtree.js.html",
    "src/lib/kdtree.js",
    "file"
  ],
  [
    "src/lib/rtree.js",
    "file/src/lib/rtree.js.html",
    "src/lib/rtree.js",
    "file"
  ],
  [
    "test/test.js",
    "test-file/test/test.js.html",
    "test/test.js",
    "testFile"
  ]
]